export const TOOLS = {
  WALL: "WALL",
  ROOM: "ROOM",
  CUSTOM_WALL: "CUSTOM_WALL",
  WALL_CUTOUT: "WALL_CUTOUT",
  FLOOR: "FLOOR",
  FLOOR_CUTOUT: "FLOOR_CUTOUT",
  HEIGHT: "HEIGHT",
  UPLOAD: "UPLOAD",
  OBJECT: "OBJECT"
};
